### ISSUE TITLE
Is it possible to install on Ubuntu from github? can't find the `.deb`

### ISSUE THREAD

**Issue by misterybodon** [leolewis/openvisualtraceroute#10]
Because sourceforge has a version from 2019 apparently

**Comment by leolewis** [comment]
Can you please try one of the deb from https://sourceforge.net/projects/openvisualtrace/files/2.0.0/ and let me know if it helps?

**Comment by leolewis** [comment]
Closing out as new versions of the deb packages have been uploaded. Please create a new ticket with specific issue if needed
