### ISSUE TITLE
MacOs Big Sur 11.2.3 OpenVisualTraceroute 2.0.0 closes just after starting

### ISSUE THREAD

**Issue by communig8-public** [leolewis/openvisualtraceroute#13]
Hello
I'm using MacOs Big Sur 11.2.3 and OpenVisualTraceroute 2.0.0.
When I run OpenVisualTraceroute.app I see it starts (icon show on task bar) but it stop with showing the UI at all.
I have tried running with OpenJDK11U-jdk_x64_mac_hotspot_11.0.14_9 and Oracle jdk-11.0.13_osx-x64_bin
but I get the same results with both.

**Comment by gdubicki** [comment]
Hey @communig8-public! You can try out my build shared here https://github.com/leolewis/openvisualtraceroute/issues/14#issuecomment-1025126685 and let me know if it works for you too.

**Comment by communig8-public** [comment]
Sorry it just behaves the same as the original version except that it does not even ask for a valid Java installation.

**Comment by leolewis** [comment]
Thanks for the report, I just uploaded a patch that might at least fix the crash at https://sourceforge.net/projects/openvisualtrace/files/2.0.0/OpenVisualTraceRoute2.0.0.dmg/download
I unfortunately don't have a Mac with a M1 CPU to test it out, if one of you could give it a try and let me know.
Thanks

**Comment by communig8-public** [comment]
Thanks that's fixed it for me

**Comment by leolewis** [comment]
can you confirm if the 3D map is working too?

**Comment by communig8-public** [comment]
Yes the 3D map is working too

**Comment by leolewis** [comment]
awesome, thanks for confirming. I'll close this ticket
