### ISSUE TITLE
2.0.0 crashes just after starting on macOS Big Sur (11.6.2)

### ISSUE THREAD

**Issue by gdubicki** [leolewis/openvisualtraceroute#14]
Hi!

I downloaded the 2.0.0 package for macOS and on start the app shows this warning first:

<img width="932" alt="Screenshot 2022-01-29 at 13 15 20" src="https://user-images.githubusercontent.com/566632/151662554-5d4e6915-4e8d-4473-ba56-b74ee860b8a3.png">

...and after clicking ok it loads the UI and immediately shows this error:

<img width="898" alt="Screenshot 2022-01-29 at 13 15 27" src="https://user-images.githubusercontent.com/566632/151662596-11aaf2c9-17e2-42a2-8482-98e719fd5c26.png">

...and closes after clicking ok here.

This is 100% reproducible.

I am using macOS Big Sur (11.6.2) on an Apple Silicon Mac with M1 chip.

**Comment by gdubicki** [comment]
After minimal fixes (#15) I was able to build the app on my own and run it with only some 3D map features missing because of some OpenGL problem. :)

[Here](https://dubhorcop.egnyte.com/dl/AIiseNol3I/OpenVisualTraceroute_2.0.0_build_2.zip_) it is, if someone wants to use it.

**Update**: ..but it's probably better to use the more standard way of installing it with homebrew, provided [here](https://github.com/leolewis/openvisualtraceroute/issues/4#issuecomment-840642290).

**Comment by leolewis** [comment]
Please try latest package from https://sourceforge.net/projects/openvisualtrace/files/2.0.0/ and let me know if it still occurs

**Comment by leolewis** [comment]
Closing as likely same issue as https://github.com/leolewis/openvisualtraceroute/issues/4
