### ISSUE TITLE
[RFE] Add support for FreeBSD

### ISSUE THREAD

**Issue by lapo-luchini** [leolewis/openvisualtraceroute#5]
Right now it just goes `Unsupported os/architecture : FreeBSD/amd64`.

**Comment by leolewis** [comment]
Thanks for the feedback. If you're still around, can you try the latest version of the universal 
package from https://sourceforge.net/projects/openvisualtrace/files/2.0.0/OpenVisualTraceRoute2.0.0.zip/download ?
I managed to run it in an Xfce GUI with the 2D map.

**Comment by lapo-luchini** [comment]
Does indeed work, thanks!

There is this warning, but I guess it's what you meant with "with the 2D map".

```
09:58:36.201 [main] INFO  org.leo.traceroute.Main - Open Visual Traceroute 2.0.0 
09:58:36.251 [main] INFO  org.leo.traceroute.install.Env - Java run-time version: 11.0.14
09:58:36.252 [main] INFO  org.leo.traceroute.install.Env - NASA WorldWind Java v2.2.0
09:58:36.253 [main] INFO  org.leo.traceroute.install.Env - Library Path /usr/lib:/usr/local/lib
09:58:36.270 [main] INFO  org.leo.traceroute.install.Env - OS:FreeBSD / arch:amd64
Locale en_GB
09:58:36.391 [main] ERROR org.leo.traceroute.install.Env - OpenGL
java.lang.UnsatisfiedLinkError: Can't load library: /home/lapo/OpenVisualTraceRoute2.0.0/natives/freebsd-amd64//libgluegen_rt.so
```

**Comment by leolewis** [comment]
Yes correct, there is no version of JOGL for freebsd available, would need to compile and package it. Until then, that's good to hear the 2D map works, thanks for confirming.
