### ISSUE TITLE
Doesn't start on Mac (but double click on JAR works!)

### ISSUE THREAD

**Issue by ogerardin** [leolewis/openvisualtraceroute#8]
MacOS Catalina 10.15.6.
Double-clicking on the app does nothing and generates the following system log entries:

````
Oct  9 17:43:57 Oliviers-MacBook-Pro com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.java.5772): Failed to bootstrap path: path = /Library/Java/JavaVirtualMachines/jdk-14.0.1.jdk/Contents/Home/bin/java, error = 2: No such file or directory
Oct  9 17:43:59 Oliviers-MacBook-Pro com.apple.xpc.launchd[1] (org.leo.traceroute.Main.72724[5772]): Service exited with abnormal code: 1
````

However if I "show package contents" and double-click on `Contents/Resources/Java/org.leo.traceroute.jar, it does start the application!

**Comment by oaxjogi** [comment]
I had no chance to commit the change on this repository, so I did it on a fork. Sorry, hate such hacks but I ran into the same issue. You can get the fix easily from https://github.com/oaxjogi/openvisualtraceroute Have fun.
BTW: If the author would give me commit rights, I would add it also here :-)

**Comment by oaxjogi** [comment]
Have created a pull request on this repository and hopefully the original author will integrate it :-)

**Comment by oaxjogi** [comment]
fixed :)

**Comment by ogerardin** [comment]
> fixed :)

Is there a release that includes the fix? I couldn't find one. I tried to build myself but it doesn't finish the build because of a change in an OS command (hdiutil I believe)

**Comment by robertoschwald** [comment]
I think it is a problem of the universalJavaApplicationStub which only supports Apple or Oracle Java.
I replaced it with the universalJavaApplicationStub from https://github.com/tofi86/universalJavaApplicationStub 
and application now starts on Big Sur using Zulu / OpenJDK. It also offers an option to install a missing JDK.

**Comment by mnbf9rca** [comment]
Is there a release with this in it? Sourceforge only contains release 1.7.1 dated 2019 - well before Big Sur
![image](https://user-images.githubusercontent.com/1039058/133426734-7406f6c2-b967-43bb-894c-ba146743a044.png)

**Comment by leolewis** [comment]
Thanks everyone, I recently released a new MacOS package with the fix, it is available at https://sourceforge.net/projects/openvisualtrace/files/2.0.0/ please git it a try and let me know if it helps.
